version: "3.8"
services:
  react-app:
    image: node:14
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "npm install &&
             npm run build"

  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./build:/usr/share/nginx/html  # Utilisation du dossier build généré par React
    depends_on:
      - react-app
